### ISSUE TITLE
WayNet Edges as Arrays - Migrated to List?

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#1]
ZenKitCS moved away from Arrays[] towards List<T>. Is it intended, that WayNet.WayEdges are an array instead of List?
I'd suggest to uniform it as WayPoints are also of type List<T>.

```c#
[Serializable]
public struct WayNet
{
	public WayEdge[] Edges;
	public List<WayPoint> Points;
}
```

**Comment by lmichaelis** [comment]
This is something I am not quite sure about. The difference comes from the way the data is exposed from C so it basically exposes an implementation detail:

https://github.com/GothicKit/ZenKitCS/blob/8016dbc007486791689aa8a19b3268bb6ad59291/ZenKit/WayNet.cs#L78-L95

Do you have a preference either way?

**Comment by JaXt0r** [comment]
I checked a few blogs. As Arrays are fixed in size, they should never be resized. As your data is fixed, this is ok.
From getting an element via index, Arrays seems slightly faster.
e.g.
* https://www.bytehide.com/blog/array-vs-list-csharp
* https://stackoverflow.com/a/44993350

Let's stick with List<> as the overhead is neglectable.

**Comment by JaXt0r** [comment]
But thinking about it...
Why not using the performance boost. Even if it's small.
As the arrays are always fixed in size from ZenKit.

Hopefully the change to Arrays is done in less than 1h for you?

**Comment by JaXt0r** [comment]
https://stackoverflow.com/a/42753399

![image](https://github.com/GothicKit/ZenKitCS/assets/120568393/b7ebfd7c-6fad-4768-b59e-366beeb76930)

**Comment by JaXt0r** [comment]
Any suggestions how you want to progress? Is List the way to go for you based on smaller performance possibilities?

**Comment by lmichaelis** [comment]
I've switched all raw arrays to Lists for now. Maybe we want to change it later but that's the easiest currently :)

**Comment by JaXt0r** [comment]
Works. Thanks.
