### ISSUE TITLE
Loading VobTree worlds (Firetree_*) throws a ZenKit Error

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#3]
Loading vobtrees throws errors
![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/178bfac3-3e44-4dca-a480-86e7dcff2e15)

![image](https://github.com/GothicVRProject/GothicVR/assets/120568393/509f1d1f-c1e4-4371-9fc8-a8bbdfa1f648)

This seems to be an error of the actual .zen files. It would be great to have an option to explicitly tell the worlds which Gothic version they have, if it can't be extracted from files itself.

**Comment by lmichaelis** [comment]
This is because the BSP-tree is used to automatically determine the version. Since it's not present in the fire VOb-trees, that will fail here. I've added the missing API in 5a7628cef00636cb986d105b7a50383458895067. Please let me know if that works for you.

**Comment by JaXt0r** [comment]
If the error log entry is gone and the file still loads, it will work. Thanks.

I'll test it asap.

**Comment by JaXt0r** [comment]
I'm not working on the fires as of today. But I didn't recognize any errors these days. I'll close the issue for now. Thanks.
