### ISSUE TITLE
Typo: SvmInstance.StoleUromMage --> StoleFromMage

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#4]
U --> F

![image](https://github.com/GothicKit/ZenKitCS/assets/120568393/f5502ea2-ca4b-44d9-8a75-c596f910cbfe)

![image](https://github.com/GothicKit/ZenKitCS/assets/120568393/b513801e-4f9c-4a3b-a74e-b08bd8329f5c)

**Comment by lmichaelis** [comment]
Done.
