### ISSUE TITLE
Item.cs needs to include "amount"

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#7]
In Gothic, an item on the surface is only drawn once, but can represent a batch of items. (e.g. dropping 13 ore from inventory will draw only one mesh).

We need to have a way to get the _amount_ information from the Vob when loaded.

**Comment by lmichaelis** [comment]
@JaXt0r it's done in ff147edb9cdab5c75bc1f42a6b4e8d16f332c5ad

**Comment by JaXt0r** [comment]
Thank you.
