### ISSUE TITLE
Object of type ZenKit.Vobs.Npc is returned as ZenKit.Vobs.VirtualObject, but could be provided as subclass directly

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#8]
When I load a save game, the Type=oCNPC is currently a VirtualObject, but could be provided as a ZenKit.Vobs.Npc already. Is there a limitation to provide the Npc subtype inside Ai property from VirtualObject (not the interface) earliest?

Current solution:
```c#

IVirtualObject iVob = ...;
VirtualObject vob = (VirtualObject)iVob; // .Ai property is only visible inside VirtualObject class, not the interface
AiHuman aiHuman = (AiHuman)vob.Ai; // Another cast needed
aiHuman.Npc; // Returns the ZenKit.Vobs.Npc
```

Expected behavior:
```c#
VirtualObject vob = ...;
Npc npc = (ZenKit.Vobs.Npc)vob; // Provides the NPC without need to find it's property inside an optiona Ai property.
```

**Comment by lmichaelis** [comment]
True! Looks like I forgot to update `VirtualObject.FromNative` when I added `Npc`

**Comment by lmichaelis** [comment]
@JaXt0r Please verify this fix.

**Comment by JaXt0r** [comment]
Works. Thanks.
