### ISSUE TITLE
StringEncodingController.SetEncoding() isn't used by Daedalus External calls (e.g. ZSpy logs)

### ISSUE THREAD

**Issue by JaXt0r** [GothicKit/ZenKitCS#9]
In our gameplay, we initially set `StringEncodingController.SetEncoding(StringEncoding.*);` unaffected by it's value, we get the following ZSpy logs:
![image](https://github.com/user-attachments/assets/3a434b7f-ac58-4d98-98c1-8d48efd98d48)
* Line 1: A normal string we fetched via loading a C_NPC instance - ok
* Line 2: A ZSpy log entry we fetch via PrintDebug*() daedalus external function - broken encoding

It seems the external functions won't get the strings encoded.

I also tested it with a plain constant from daedalus. And I can directly read a cyrillic value like this. So normal string usage works with the StringEncodingController:
```c#
// We fetch one symbol from G1 which is translated differently in every language. With this, we can auto-suggest the used game language.
StringEncodingController.SetEncoding(StringEncoding.EastEurope);
var l10nSymbol = GameData.GothicVm.GetSymbolByName("MOBNAME_CRATE");
var l10nString = l10nSymbol.GetString(0);
Debug.Log(l10nString); // for russian:  Коробка - ok
```

**ASK:**  
Can you please check if the encoding is being used for strings returned by Daedalus external functions?

**Comment by lmichaelis** [comment]
It is using the correct function: 
![bilde](https://github.com/user-attachments/assets/4ea0dc74-aa7f-4934-bd00-9f7b3792f1ae)
![bilde](https://github.com/user-attachments/assets/b97230fd-98aa-4f3b-876c-24eba7443e24)

**Comment by JaXt0r** [comment]
Hm... Did you test it on your end if it produces the same wrong behavior? If you provide a quick test on ZK.Tests, I can check it on my end later as well.

**Comment by JaXt0r** [comment]
Your fix solved the issue. Thanks.
